[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions/dist"

[functions]
  directory = "netlify/functions/dist"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_URL = ""  # Will be set based on environment
  NPM_CONFIG_PRODUCTION = "false"  # This ensures devDependencies are installed

[dev]
  framework = "#custom"
  command = "npm run dev"  # Command to start the development server
  targetPort = 3000       # Frontend port
  port = 5000             # Backend port for Netlify Dev
  publish = "dist/public"
  autoLaunch = true

# API proxy - must come before the SPA fallback
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA fallback - must come after API routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.stripe.com; connect-src 'self' https://api.stripe.com; frame-src 'self' https://js.stripe.com https://hooks.stripe.com;"

# CORS headers for API
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle 500s for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 500
  force = false

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
