# Global build settings
[build]
  command = "npm run build"
  publish = "./dist"

# Environment variables
[build.environment]
  # Node.js version
  NODE_VERSION = "22"
  
  # NPM configuration
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERBOSE = "true"
  NPM_CONFIG_PRODUCTION = "false"
  
  # Security settings - Disable secrets scanning for now
  SECRETS_SCAN_ENABLED = "false"
  
  # Build settings
  NETLIFY_USE_YARN = "false"
  YARN_FLAGS = ""
  YARN_VERBOSE = "false"
  YARN_NETWORK_TIMEOUT = "600000"
  
  # Application environment variables
  # These should be set in Netlify UI
  NODE_ENV = "production"
  
  # These values will be overridden by Netlify UI environment variables
  VITE_STRIPE_PUBLISHABLE_KEY = ""
  VITE_API_URL = ""
  FRONTEND_URL = ""

# Environment-specific settings
[context.production]
  command = "npm run build"
  publish = "./dist"
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "development"

[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"

# Development server settings
[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
