# Global build settings
[build]
  command = "npm run build && cd netlify/functions && npm install && npm run build && cd ../.."
  publish = "./dist"
  functions = "./netlify/functions/dist"
  base = "/"

[functions]
  # Set the Node.js version for Netlify Functions
  node_bundler = "esbuild"
  
  # Environment variables for Netlify Functions
  [functions.environment]
    NODE_ENV = "production"
    
  # Include source maps for better error reporting
  external_node_modules = ["@netlify/functions"]
  
  # Set the directory where the built functions are located
  directory = "netlify/functions/dist"

# Environment variables
[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # NPM configuration
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERBOSE = "true"
  NPM_CONFIG_PRODUCTION = "false"
  
  # Security settings
  SECRETS_SCAN_ENABLED = "true"
  
  # Build settings
  NETLIFY_USE_YARN = "false"
  YARN_FLAGS = ""
  YARN_VERBOSE = "false"
  YARN_NETWORK_TIMEOUT = "600000"
  
  # Application environment variables
  NODE_ENV = "production"
  
  # Build environment variables
  VITE_API_URL = "/.netlify/functions/api"
  
  # These values should be set in Netlify UI
  VITE_STRIPE_PUBLISHABLE_KEY = ""
  FRONTEND_URL = ""
  
  # Server-side environment variables
  STRIPE_SECRET_KEY = ""
  STRIPE_WEBHOOK_SECRET = ""
  SESSION_SECRET = ""
  
  # Build optimization
  NODE_OPTIONS = "--max_old_space_size=4096"
  
  # Enable source maps for debugging
  GENERATE_SOURCEMAP = "true"

# Environment-specific settings
[context.production]
  command = "npm run build"
  publish = "./dist"
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "development"

[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"

# Development server settings
[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "./dist"
  
  # Environment variables for development
  [dev.environment]
    NODE_ENV = "development"
    VITE_API_URL = "http://localhost:5001"
    VITE_STRIPE_PUBLISHABLE_KEY = ""
    FRONTEND_URL = "http://localhost:5173"

# Redirects for SPA and API
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = "!Function"}

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle CORS preflight requests
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.stripe.com; connect-src 'self' https://api.stripe.com; frame-src 'self' https://js.stripe.com https://hooks.stripe.com;"

# CORS headers for API
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Sitemap and robots.txt handling
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for API responses
[[headers]]
  for = "/*.js"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Enable CORS for development
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Handle 404s for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = false

# Handle 403s for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 403
  force = false

# Handle 500s for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 500
  force = false

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
