[build]
  command = "cd client && npm install --include=dev && cd .. && npm run build"
  publish = "dist/public"
  functions = "netlify/functions/dist"

[functions]
  directory = "netlify/functions/dist"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_URL = "/.netlify/functions/api"
  NPM_CONFIG_PRODUCTION = "false"  # This ensures devDependencies are installed

[dev]
  framework = "vite"
  target = "static"
  command = "npm run dev"
  port = 8888  # Changed from 5173 to avoid conflict
  publish = "dist/public"
  functions = "netlify/functions/dist"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.stripe.com; connect-src 'self' https://api.stripe.com; frame-src 'self' https://js.stripe.com https://hooks.stripe.com;"

# CORS headers for API
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle 500s for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 500
  force = false

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
